// Regenerates supabase/seed.sql from the built-in content in lib/.
// Run: node scripts/generate-seed.mts
import { writeFileSync } from "node:fs";
import { defaultChatConfig } from "../lib/assistant.ts";
import { defaultPostContents } from "../lib/post-contents.ts";
import { defaultPosts } from "../lib/posts.ts";
import { defaultProductCategories } from "../lib/products.ts";
import { defaultProjects } from "../lib/projects.ts";
import { defaultContactSettings } from "../lib/site.ts";

const q = (value: string | number | boolean) =>
  typeof value === "string" ? `'${value.replaceAll("'", "''")}'` : String(value);
const arr = (values: string[]) => `array[${values.map(q).join(", ")}]::text[]`;
const json = (value: object) => `${q(JSON.stringify(value))}::jsonb`;

const lines = [
  "-- Imports the current site content. Generated by scripts/generate-seed.mts; safe to re-run (keeps existing rows; only fills empty article bodies).",
  "",
  ...defaultPosts.map(
    (p) =>
      `insert into public.posts (slug, title, date, excerpt, content, image_url, image_width, image_height, comments) values (${[
        p.slug, p.title, p.date, p.excerpt, defaultPostContents[p.slug] ?? "", p.image.src, p.image.width, p.image.height, p.comments,
      ].map(q).join(", ")}) on conflict (slug) do update set content = excluded.content where public.posts.content = '';`,
  ),
  "",
  ...defaultProductCategories.map(
    (c, i) =>
      `insert into public.product_categories (slug, title, meta_description, sort_order) values (${[
        c.slug, c.title, c.metaDescription, i,
      ].map(q).join(", ")}) on conflict (slug) do nothing;`,
  ),
  "",
  "do $$ begin if not exists (select 1 from public.products) then",
  ...defaultProductCategories.flatMap((c) =>
    c.products.map(
      (p, i) =>
        `  insert into public.products (category_slug, name, description, price, price_size, images, sort_order) values (${[
          q(c.slug), q(p.name), q(p.description), q(p.price), q(p.priceSize), arr(p.images), q(i),
        ].join(", ")});`,
    ),
  ),
  "end if; end $$;",
  "",
  "do $$ begin if not exists (select 1 from public.projects) then",
  ...defaultProjects.map(
    (p, i) =>
      `  insert into public.projects (name, location, image, sort_order) values (${[p.name, p.location, p.image, i]
        .map(q)
        .join(", ")});`,
  ),
  "end if; end $$;",
  "",
  `insert into public.settings (key, value) values ('contact', ${json(defaultContactSettings)}) on conflict (key) do nothing;`,
  `insert into public.settings (key, value) values ('chat', ${json(defaultChatConfig)}) on conflict (key) do nothing;`,
  "",
];

writeFileSync(new URL("../supabase/seed.sql", import.meta.url), lines.join("\n"));
console.log("Wrote supabase/seed.sql");
